server:
  port: 8081
#≈‰÷√ ˝æ›‘¥
spring:
  datasource:
    url: jdbc:mysql://116.62.20.242:3306/cloud_note?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 115z6311.13S
    driver-class-name: com.mysql.jdbc.Driver
